# Generated by Django 6.0.1 on 2026-01-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_number', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=10)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_pumps.pump')),
            ],
        ),
    ]
