# Generated by Django 6.0.1 on 2026-01-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_pumps', '0002_nozzle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('liters_sold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rate_per_liter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_pumps.nozzle')),
            ],
        ),
    ]
